module.exports = (sequelize, DataTypes) => {

	const User = sequelize.define('ims_mc_members', {
        email: DataTypes.STRING,
        mobile:DataTypes.INTEGER,
    	password: DataTypes.STRING,
    	uid:{
    		type: DataTypes.INTEGER,
	        primaryKey: true,
	        autoIncrement: true,
    	},
        salt: DataTypes.STRING,
        uniacid:DataTypes.INTEGER,
        groupid:DataTypes.INTEGER,
        credit1: DataTypes.DECIMAL(10, 2),
        credit2: DataTypes.DECIMAL(10, 2),
        credit3: DataTypes.DECIMAL(10, 2),
        credit4: DataTypes.DECIMAL(10, 2),
        credit5: DataTypes.DECIMAL(10, 2),
        credit6: DataTypes.DECIMAL(10, 2),
        createtime:DataTypes.INTEGER,
        realname: DataTypes.STRING,
        nickname: DataTypes.STRING,
        avatar: DataTypes.STRING,
        qq: DataTypes.STRING,
        vip:DataTypes.INTEGER,
        gender:DataTypes.INTEGER,
        birthyear:DataTypes.INTEGER,
          birthmonth:DataTypes.INTEGER,
          birthday:DataTypes.INTEGER,
          constellation:DataTypes.STRING,
          zodiac:DataTypes.STRING,
          telephone:DataTypes.STRING,
          idcard:DataTypes.STRING,
          studentid:DataTypes.STRING,
          grade:DataTypes.STRING,
          address:DataTypes.STRING,
          zipcode:DataTypes.STRING,
          nationality:DataTypes.STRING,
          resideprovince:DataTypes.STRING,
          residecity:DataTypes.STRING,
          residedist:DataTypes.STRING,
          graduateschool:DataTypes.STRING,
          company:DataTypes.STRING,
          education:DataTypes.STRING,
          occupation:DataTypes.STRING,
          position:DataTypes.STRING,
          revenue:DataTypes.STRING,
          affectivestatus:DataTypes.STRING,
          lookingfor:DataTypes.STRING,
          bloodtype:DataTypes.STRING,
          height:DataTypes.STRING,
          weight:DataTypes.STRING,
          alipay:DataTypes.STRING,
          msn:DataTypes.STRING,
          taobao:DataTypes.STRING,
          site:DataTypes.STRING,
          bio:DataTypes.TEXT,
          interest:DataTypes.TEXT,
    },{
    	freezeTableName: true,
    	timestamps: false,
    });
  return User;
};
